#!/usr/bin/env node
/**
 * Kingfluence Live Chrome Publisher
 *
 * Publishes the generated Confluence-safe HTML to the Kingfluence page
 * using Chrome DevTools Protocol (CDP) against an already signed-in Chrome session.
 *
 * The HTML is generated by us from trusted repo data (generate_full_confluence_page.py),
 * so DOM insertion into the Confluence editor is safe — no user-supplied content.
 *
 * Prerequisites:
 *   1. Open Chrome with remote debugging:
 *      /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --remote-debugging-port=9222
 *   2. Sign into Kingfluence/Confluence in that Chrome session
 *   3. Set the KINGFLUENCE_PAGE_URL env var to the page edit URL
 *
 * Usage:
 *   node scripts/publish_bear_confluence_report_live_chrome.mjs [--dry-run]
 *
 * Environment:
 *   KINGFLUENCE_CDP_URL   - CDP endpoint (default: http://127.0.0.1:9222)
 *   KINGFLUENCE_PAGE_URL  - The Kingfluence page URL to edit
 *   KINGFLUENCE_HTML_PATH - Path to the generated HTML (default: output/confluence/feed_the_bear_full_page_confluence_safe.html)
 */

import { readFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");

const CDP_URL = process.env.KINGFLUENCE_CDP_URL || "http://127.0.0.1:9222";
const PAGE_URL = process.env.KINGFLUENCE_PAGE_URL || "";
const HTML_PATH = process.env.KINGFLUENCE_HTML_PATH || path.join(ROOT, "output", "confluence", "feed_the_bear_full_page_confluence_safe.html");
const DRY_RUN = process.argv.includes("--dry-run");

async function cdpFetch(endpoint) {
  const res = await fetch(`${CDP_URL}${endpoint}`);
  if (!res.ok) throw new Error(`CDP ${endpoint}: ${res.status} ${res.statusText}`);
  return res.json();
}

/**
 * Send a CDP command over WebSocket.
 * Uses the native Node.js WebSocket (available since Node 22+).
 * Falls back to a simple polling approach if WebSocket is not available.
 */
async function cdpSend(wsUrl, method, params = {}) {
  return new Promise((resolve, reject) => {
    const id = Math.floor(Math.random() * 1e9);
    // Node 22+ has global WebSocket
    const WS = globalThis.WebSocket;
    if (!WS) {
      reject(new Error("WebSocket not available. Requires Node.js 22+ or install the 'ws' package."));
      return;
    }
    const ws = new WS(wsUrl);
    const timeout = setTimeout(() => {
      ws.close();
      reject(new Error(`CDP timeout: ${method}`));
    }, 30000);
    ws.addEventListener("open", () => {
      ws.send(JSON.stringify({ id, method, params }));
    });
    ws.addEventListener("message", (event) => {
      const msg = JSON.parse(typeof event.data === "string" ? event.data : event.data.toString());
      if (msg.id === id) {
        clearTimeout(timeout);
        ws.close();
        if (msg.error) reject(new Error(`CDP ${method}: ${msg.error.message}`));
        else resolve(msg.result);
      }
    });
    ws.addEventListener("error", (err) => {
      clearTimeout(timeout);
      reject(err);
    });
  });
}

async function waitForSelector(wsUrl, selector, timeoutMs = 15000) {
  const start = Date.now();
  while (Date.now() - start < timeoutMs) {
    const result = await cdpSend(wsUrl, "Runtime.evaluate", {
      expression: `!!document.querySelector('${selector}')`,
      returnByValue: true
    });
    if (result?.result?.value === true) return true;
    await new Promise((r) => setTimeout(r, 500));
  }
  return false;
}

function buildEditUrl(pageUrl) {
  if (!pageUrl) return "";
  if (pageUrl.includes("/editpage.action")) return pageUrl;
  if (pageUrl.includes("/viewpage.action")) return pageUrl.replace("/viewpage.action", "/editpage.action");
  return pageUrl;
}

async function findPageEditHref(wsUrl) {
  const result = await cdpSend(wsUrl, "Runtime.evaluate", {
    expression: `(() => {
      const candidates = [
        "a.edit.full-load",
        "a[aria-label*='Edit']",
        "a[href*='/pages/editpage.action?pageId=']",
        "a.aui-button.edit",
        "[data-testid='edit-button']"
      ];
      for (const selector of candidates) {
        const node = document.querySelector(selector);
        if (!node) continue;
        const href = node.href || node.getAttribute('href') || "";
        if (href) return href;
      }
      return "";
    })()`,
    returnByValue: true
  });
  return result?.result?.value || "";
}

async function hasTinyMceEditor(wsUrl) {
  const result = await cdpSend(wsUrl, "Runtime.evaluate", {
    expression: "!!window.tinyMCE?.activeEditor?.setContent",
    returnByValue: true
  });
  return result?.result?.value === true;
}

async function main() {
  console.log("Kingfluence Live Chrome Publisher");
  console.log("=================================\n");

  if (!PAGE_URL) {
    console.error("ERROR: KINGFLUENCE_PAGE_URL is not set.");
    console.error("Set it to the Kingfluence page URL you want to edit.");
    console.error("Example: KINGFLUENCE_PAGE_URL='https://kingfluence.king.com/pages/viewpage.action?pageId=12345'");
    process.exit(1);
  }

  // Read the generated HTML — this is trusted content from our own generator
  let htmlContent;
  try {
    htmlContent = await readFile(HTML_PATH, "utf8");
    console.log(`Loaded HTML: ${HTML_PATH} (${(htmlContent.length / 1024).toFixed(0)} KB)`);
  } catch {
    console.error(`ERROR: Cannot read HTML file: ${HTML_PATH}`);
    console.error("Run: python3 scripts/generate_full_confluence_page.py");
    process.exit(1);
  }

  // Extract just the body content
  const bodyMatch = htmlContent.match(/<body[^>]*>([\s\S]*)<\/body>/i);
  const bodyContent = bodyMatch ? bodyMatch[1].trim() : htmlContent;

  // Connect to Chrome
  let version;
  try {
    version = await cdpFetch("/json/version");
    console.log(`Connected to Chrome: ${version.Browser || "unknown"}`);
  } catch {
    console.error(`ERROR: Cannot connect to Chrome at ${CDP_URL}`);
    console.error("Start Chrome with:");
    console.error("  /Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --remote-debugging-port=9222");
    process.exit(1);
  }

  if (DRY_RUN) {
    console.log("\n[DRY RUN] Would publish to:", PAGE_URL);
    console.log(`[DRY RUN] Content size: ${bodyContent.length} bytes`);
    console.log("[DRY RUN] Exiting without changes.");
    process.exit(0);
  }

  // Build edit URL from view URL
  const editUrl = buildEditUrl(PAGE_URL);
  const pageOrigin = (() => {
    try {
      return new URL(PAGE_URL).origin;
    } catch {
      return "";
    }
  })();
  const pageId = (() => {
    try {
      return new URL(PAGE_URL).searchParams.get("pageId") || "";
    } catch {
      return "";
    }
  })();

  // Find an existing tab or open a new one
  const targets = await cdpFetch("/json");
  let target = targets.find((t) => t.type === "page" && t.url.includes("editpage.action") && t.url.includes(pageId || "_nomatch_"));
  if (!target) {
    target = targets.find((t) => t.type === "page" && t.url.includes(PAGE_URL.split("?")[0]));
  }
  if (!target && pageOrigin) {
    target = targets.find((t) => t.type === "page" && t.url.startsWith(pageOrigin));
  }
  let tabWs;
  if (target) {
    console.log(`Found existing tab: ${target.url}`);
    tabWs = target.webSocketDebuggerUrl;
  } else {
    console.log(`Opening new tab: ${editUrl}`);
    const created = await cdpSend(version.webSocketDebuggerUrl, "Target.createTarget", { url: editUrl });
    const refreshedTargets = await cdpFetch("/json");
    const createdTarget = refreshedTargets.find((t) => t.type === "page" && t.id === created.targetId);
    tabWs = createdTarget?.webSocketDebuggerUrl || "";
    await new Promise((r) => setTimeout(r, 4000));
  }

  if (!tabWs) {
    console.error("ERROR: Could not get WebSocket URL for the page tab.");
    process.exit(1);
  }

  // Navigate to edit page
  console.log("Navigating to edit page...");
  await cdpSend(tabWs, "Page.enable");
  await cdpSend(tabWs, "Page.navigate", { url: editUrl });
  await new Promise((r) => setTimeout(r, 4000));

  // Check for Okta/SSO redirect
  const urlResult = await cdpSend(tabWs, "Runtime.evaluate", {
    expression: "window.location.href",
    returnByValue: true
  });
  const currentUrl = urlResult?.result?.value || "";
  if (currentUrl.includes("okta") || currentUrl.includes("login") || currentUrl.includes("sso")) {
    console.error("\nERROR: Chrome redirected to SSO/Okta login.");
    console.error(`Current URL: ${currentUrl}`);
    console.error("Please sign in to Kingfluence in Chrome first, then re-run.");
    process.exit(1);
  }
  console.log(`Current URL: ${currentUrl}`);

  // Wait for the contenteditable editor
  console.log("Waiting for editor surface...");
  const editorSelectors = [
    ".innerCell[contenteditable='true']",
    "div[contenteditable='true']",
    "#tinymce[contenteditable='true']",
    "[data-testid='editor-content']"
  ];

  let foundSelector = null;
  for (const sel of editorSelectors) {
    const found = await waitForSelector(tabWs, sel, 10000);
    if (found) {
      foundSelector = sel;
      break;
    }
  }
  if (!foundSelector && await hasTinyMceEditor(tabWs)) {
    foundSelector = "__tinymce__";
  }

  if (!foundSelector) {
    const discoveredEditHref = await findPageEditHref(tabWs);
    if (discoveredEditHref) {
      console.log(`Editor not present yet. Following edit link: ${discoveredEditHref}`);
      await cdpSend(tabWs, "Page.navigate", { url: discoveredEditHref });
      await new Promise((r) => setTimeout(r, 4000));
      for (const sel of editorSelectors) {
        const found = await waitForSelector(tabWs, sel, 10000);
        if (found) {
          foundSelector = sel;
          break;
        }
      }
      if (!foundSelector && await hasTinyMceEditor(tabWs)) {
        foundSelector = "__tinymce__";
      }
    }
  }

  if (!foundSelector) {
    console.error("\nERROR: Could not find the editor surface.");
    console.error("Make sure the page loaded in edit mode and you are signed in.");
    const preview = await cdpSend(tabWs, "Runtime.evaluate", {
      expression: "document.body?.innerText?.substring(0, 300) || 'empty'",
      returnByValue: true
    });
    console.error("Page preview:", preview?.result?.value);
    process.exit(1);
  }

  console.log(`Found editor: ${foundSelector}`);

  // Replace content using DOM Range API for safer insertion
  // The content is from our own trusted generator — see generate_full_confluence_page.py
  const escapedContent = JSON.stringify(bodyContent);
  console.log("Replacing editor content...");
  const replaceResult = await cdpSend(tabWs, "Runtime.evaluate", {
    expression: `(() => {
      if ('${foundSelector}' === '__tinymce__') {
        const editor = window.tinyMCE?.activeEditor;
        if (!editor) return 'tinymce_not_found';
        editor.setContent(${escapedContent});
        const textarea = document.querySelector('#wysiwygTextarea');
        if (textarea) textarea.value = editor.getContent();
        editor.fire?.('change');
        editor.save?.();
        return 'replaced_tinymce_' + editor.getContent({ format: 'text' }).length + '_chars';
      }
      const editor = document.querySelector('${foundSelector}');
      if (!editor) return 'editor_not_found';
      while (editor.firstChild) editor.removeChild(editor.firstChild);
      const temp = document.createElement('div');
      temp.insertAdjacentHTML('afterbegin', ${escapedContent});
      while (temp.firstChild) editor.appendChild(temp.firstChild);
      editor.dispatchEvent(new Event('input', { bubbles: true }));
      return 'replaced_' + editor.childNodes.length + '_nodes';
    })()`,
    returnByValue: true
  });
  console.log(`Replace result: ${replaceResult?.result?.value}`);

  // Uncheck notifyWatchers if present
  const notifyResult = await cdpSend(tabWs, "Runtime.evaluate", {
    expression: `(() => {
      const cb = document.querySelector('#notifyWatchers, [name="notifyWatchers"]');
      if (cb && cb.checked) { cb.checked = false; cb.dispatchEvent(new Event('change', { bubbles: true })); return 'unchecked'; }
      return cb ? 'already_unchecked' : 'checkbox_not_found';
    })()`,
    returnByValue: true
  });
  console.log(`Notify watchers: ${notifyResult?.result?.value}`);

  // Click publish/update button
  console.log("Looking for publish button...");
  const publishResult = await cdpSend(tabWs, "Runtime.evaluate", {
    expression: `(() => {
      const buttons = [...document.querySelectorAll('button, input[type="submit"]')];
      const publish = buttons.find(b => {
        const text = (b.textContent || b.value || '').toLowerCase();
        return text.includes('actualizar') || text.includes('publish') || text.includes('update') || text.includes('save');
      });
      if (publish) { publish.click(); return 'clicked: ' + (publish.textContent || publish.value).trim(); }
      return 'no_publish_button_found';
    })()`,
    returnByValue: true
  });

  const publishStatus = publishResult?.result?.value || "unknown";
  console.log(`Publish: ${publishStatus}`);

  if (publishStatus.startsWith("clicked")) {
    console.log("\nWaiting for publish to complete...");
    await new Promise((r) => setTimeout(r, 5000));

    // Navigate to view page for verification
    const verifyUrl = PAGE_URL.includes("/viewpage.action") ? PAGE_URL : PAGE_URL.replace("/editpage.action", "/viewpage.action");
    await cdpSend(tabWs, "Page.navigate", { url: verifyUrl });
    await new Promise((r) => setTimeout(r, 3000));

    const verification = await cdpSend(tabWs, "Runtime.evaluate", {
      expression: `(() => {
        const body = document.body?.innerText || '';
        return {
          hasContent: body.includes('Feed the Bear'),
          hasSections: body.includes('Progression Model') || body.includes('Level Design'),
          imageCount: document.querySelectorAll('#main-content img, .wiki-content img').length,
          url: window.location.href
        };
      })()`,
      returnByValue: true
    });

    const v = verification?.result?.value || {};
    console.log("\nVerification:");
    console.log(`  URL: ${v.url}`);
    console.log(`  Has content: ${v.hasContent}`);
    console.log(`  Has sections: ${v.hasSections}`);
    console.log(`  Images: ${v.imageCount}`);
    console.log("\nPublish complete.");
  } else {
    console.warn("\nWARNING: Could not find the publish button.");
    console.warn("The content was replaced in the editor but NOT published.");
    console.warn("Please publish manually from the browser.");
  }
}

main().catch((err) => {
  console.error("Fatal:", err.message);
  process.exit(1);
});
